In [1]:
from urllib import request
from bs4 import BeautifulSoup

In [2]:
target = request.urlopen("https://www.naver.com")
soup=BeautifulSoup(target,"html.parser")
rank=soup.find("ul",class_="ah_l")
for i in rank.find_all("li"):
    print(i.get_text("위 : ", strip=True))

1위 : 프라엘플러스
2위 : 안다르 있지 스트릿
3위 : 우신사 안다르 있지
4위 : 웨이브1년무료
5위 : 포에버21
6위 : 안다르 있지
7위 : 노르딕슬립
8위 : lg프라엘
9위 : 빅토리아
10위 : 설리 동향보고
11위 : 정동병원
12위 : lg 프라엘 플러스
13위 : 김도읍
14위 : lg 프라엘 마스크
15위 : 인터파크 인생날
16위 : 보타닉힐보 프로바이오덤
17위 : 엔플라잉 굿밤
18위 : 백혜련
19위 : 국일제지
20위 : 정점식

In [3]:
from urllib import request
from bs4 import BeautifulSoup

target=request.urlopen("https://movie.naver.com/movie/sdb/rank/rmovie.nhn")
soup=BeautifulSoup(target,"html.parser")
rank=soup.find("table",class_="list_ranking")
num=1
for i in rank.find_all("div"):
    print(num, i.get_text("위 :", strip=True))
    num+=1

1 조커
2 가장 보통의 연애
3 양자물리학
4 제미니 맨
5 퍼펙트맨
6 판소리 복서
7 타짜: 원 아이드 잭
8 82년생 김지영
9 장사리 : 잊혀진 영웅들
10 너를 만난 여름
11 두번할까요
12 말레피센트 2
13 버티고
14 나쁜 녀석들: 더 무비
15 벌새
16 잃어버린 세계를 찾아서
17 원스 어폰 어 타임... 인 할리우드
18 아이언 자이언트
19 더 룸
20 신문기자
21 터미네이터: 다크 페이트
22 다크 나이트
23 메기
24 라이온 킹
25 대범죄도시: 나쁜녀석들
26 신의 한 수: 귀수편
27 열두 번째 용의자
28 소피와 드래곤: 마법책의 비밀
29 힘을 내요, 미스터 리
30 광대들: 풍문조작단
31 수상한 이웃
32 와일드 로즈
33 토막살인범의 고백
34 그것: 두 번째 이야기
35 기생충
36 블러드 심플
37 람보 : 라스트 워
38 날씨의 아이
39 쿵푸 보이
40 그녀
41 겨울왕국 2
42 몬스터 하우스
43 버즈 오브 프레이(할리퀸의 황홀한 해방)
44 완벽한 타인
45 뺑반
46 리얼
47 타짜
48 엑시트
49 여수 밤바다
50 재혼의 기술

In [5]:
import random 
for i in range(100):
    print(int(random.random()*10), end=' ')

l=[]
count=0
while count < 6:
    a=int(random.random()*100)
    if (a <46) * (a>0):
        if (count==0):
            l.append(a)
            count+=1
        else:
            for i in range(0,count):
                if a ==l[i]:
                    break;
            l.append(a)
            count+=1
print(l)

l=[]
count=0
while count<6:
    tmp = random.randint(1,45)
    if (tmp not in l):
        l.append(tmp)
        count +=1

random.sample(range(1,45),6)

4 9 5 1 4 2 7 9 0 2 2 4 0 9 7 3 4 1 0 8 9 5 8 4 4 1 9 8 6 4 1 7 1 9 8 2 4 2 4 7 6 2 3 7 4 6 7 7 9 1 3 8 0 3 1 7 9 8 6 6 5 3 0 6 5 2 9 1 3 6 2 1 5 7 3 7 9 6 4 6 0 7 3 5 4 9 9 7 3 3 1 6 4 4 7 7 0 1 1 1 [20, 20, 2, 33, 32, 24]

[27, 5, 22, 40, 23, 26]

# 구구단

In [7]:
for i in range(2,20):
    for j in range(1,20):
        print("{} * {} = {}" .format(i,j,i*j))

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
2 * 11 = 22
2 * 12 = 24
2 * 13 = 26
2 * 14 = 28
2 * 15 = 30
2 * 16 = 32
2 * 17 = 34
2 * 18 = 36
2 * 19 = 38
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
3 * 11 = 33
3 * 12 = 36
3 * 13 = 39
3 * 14 = 42
3 * 15 = 45
3 * 16 = 48
3 * 17 = 51
3 * 18 = 54
3 * 19 = 57
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
4 * 11 = 44
4 * 12 = 48
4 * 13 = 52
4 * 14 = 56
4 * 15 = 60
4 * 16 = 64
4 * 17 = 68
4 * 18 = 72
4 * 19 = 76
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
5 * 11 = 55
5 * 12 = 60
5 * 13 = 65
5 * 14 = 70
5 * 15 = 75
5 * 16 = 80
5 * 17 = 85
5 * 18 = 90
5 * 19 = 95
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
6 * 11 = 66
6 * 12 = 72
6 * 13 = 78
6 * 14 = 84
6 * 15 = 90
6 * 16 = 96
6 * 17 = 102
6 * 18 = 108
6 * 19 = 114
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
7 * 11 = 77
7 * 12 = 84
7 * 13 = 91
7 * 14 = 98
7 * 15 = 105
7 * 16 = 112
7 * 17 = 119
7 * 18 = 126
7 * 19 = 133
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80
8 * 11 = 88
8 * 12 = 96
8 * 13 = 104
8 * 14 = 112
8 * 15 = 120
8 * 16 = 128
8 * 17 = 136
8 * 18 = 144
8 * 19 = 152
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
9 * 11 = 99
9 * 12 = 108
9 * 13 = 117
9 * 14 = 126
9 * 15 = 135
9 * 16 = 144
9 * 17 = 153
9 * 18 = 162
9 * 19 = 171
10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100
10 * 11 = 110
10 * 12 = 120
10 * 13 = 130
10 * 14 = 140
10 * 15 = 150
10 * 16 = 160
10 * 17 = 170
10 * 18 = 180
10 * 19 = 190
11 * 1 = 11
11 * 2 = 22
11 * 3 = 33
11 * 4 = 44
11 * 5 = 55
11 * 6 = 66
11 * 7 = 77
11 * 8 = 88
11 * 9 = 99
11 * 10 = 110
11 * 11 = 121
11 * 12 = 132
11 * 13 = 143
11 * 14 = 154
11 * 15 = 165
11 * 16 = 176
11 * 17 = 187
11 * 18 = 198
11 * 19 = 209
12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120
12 * 11 = 132
12 * 12 = 144
12 * 13 = 156
12 * 14 = 168
12 * 15 = 180
12 * 16 = 192
12 * 17 = 204
12 * 18 = 216
12 * 19 = 228
13 * 1 = 13
13 * 2 = 26
13 * 3 = 39
13 * 4 = 52
13 * 5 = 65
13 * 6 = 78
13 * 7 = 91
13 * 8 = 104
13 * 9 = 117
13 * 10 = 130
13 * 11 = 143
13 * 12 = 156
13 * 13 = 169
13 * 14 = 182
13 * 15 = 195
13 * 16 = 208
13 * 17 = 221
13 * 18 = 234
13 * 19 = 247
14 * 1 = 14
14 * 2 = 28
14 * 3 = 42
14 * 4 = 56
14 * 5 = 70
14 * 6 = 84
14 * 7 = 98
14 * 8 = 112
14 * 9 = 126
14 * 10 = 140
14 * 11 = 154
14 * 12 = 168
14 * 13 = 182
14 * 14 = 196
14 * 15 = 210
14 * 16 = 224
14 * 17 = 238
14 * 18 = 252
14 * 19 = 266
15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150
15 * 11 = 165
15 * 12 = 180
15 * 13 = 195
15 * 14 = 210
15 * 15 = 225
15 * 16 = 240
15 * 17 = 255
15 * 18 = 270
15 * 19 = 285
16 * 1 = 16
16 * 2 = 32
16 * 3 = 48
16 * 4 = 64
16 * 5 = 80
16 * 6 = 96
16 * 7 = 112
16 * 8 = 128
16 * 9 = 144
16 * 10 = 160
16 * 11 = 176
16 * 12 = 192
16 * 13 = 208
16 * 14 = 224
16 * 15 = 240
16 * 16 = 256
16 * 17 = 272
16 * 18 = 288
16 * 19 = 304
17 * 1 = 17
17 * 2 = 34
17 * 3 = 51
17 * 4 = 68
17 * 5 = 85
17 * 6 = 102
17 * 7 = 119
17 * 8 = 136
17 * 9 = 153
17 * 10 = 170
17 * 11 = 187
17 * 12 = 204
17 * 13 = 221
17 * 14 = 238
17 * 15 = 255
17 * 16 = 272
17 * 17 = 289
17 * 18 = 306
17 * 19 = 323
18 * 1 = 18
18 * 2 = 36
18 * 3 = 54
18 * 4 = 72
18 * 5 = 90
18 * 6 = 108
18 * 7 = 126
18 * 8 = 144
18 * 9 = 162
18 * 10 = 180
18 * 11 = 198
18 * 12 = 216
18 * 13 = 234
18 * 14 = 252
18 * 15 = 270
18 * 16 = 288
18 * 17 = 306
18 * 18 = 324
18 * 19 = 342
19 * 1 = 19
19 * 2 = 38
19 * 3 = 57
19 * 4 = 76
19 * 5 = 95
19 * 6 = 114
19 * 7 = 133
19 * 8 = 152
19 * 9 = 171
19 * 10 = 190
19 * 11 = 209
19 * 12 = 228
19 * 13 = 247
19 * 14 = 266
19 * 15 = 285
19 * 16 = 304
19 * 17 = 323
19 * 18 = 342
19 * 19 = 361